name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "af95fd016b3249a184791ac6a2607916" },
  { binding = "SHARE", id = "b1e63fff72ed4c2d851cdf97f6320658" }
]