// static CDN
export const CDN_PREFIX =
  "//fastly.jsdelivr.net/gh/fangyuan99/serverless-cloud-notepad@master/static";

// server side salt
export const SALT = SCN_SALT;
// server side secret
export const SECRET = SCN_SECRET;

// supported language
export const SUPPORTED_LANG = {
  en: {
    setPW: "Set Password",
    changePW: "Change Password",
    share: "Share",
    lastModified: "Last Modified",
    copy: "Copy",
    emptyPH: "There are many like it, but this one is mine...",
    tipEncrypt: "This Note has been encrypted, please enter password!",
    tip404: "404, Nothing here",
    backup: "Backup",
    restore: "Restore",
    export_: "Export",
    import_: "Import",
    encrypt: "Encrypt",
    close: "Close",
    webdavConfig: "WebDAV Config",
    webdavUrl: "WebDAV URL",
    username: "Username",
    password: "Password",
    basePath: "Base Path",
    saveConfig: "Save Config",
    testConn: "Test Connection",
    backupNow: "Backup Now",
    backupList: "Backup List",
    noBackups: "No backups yet",
    confirmRestore: "Restore this backup? Current content will be overwritten.",
    encryptPw: "Encryption Password",
    invalidFile: "Invalid backup file",
    wrongPassword: "Wrong password or corrupted file",
    exportSuccess: "Exported successfully",
    importSuccess: "Imported successfully",
    backupSuccess: "Backup successful",
    restoreSuccess: "Restored successfully",
    connSuccess: "Connection successful",
    connFailed: "Connection failed",
    localBackup: "Local Export/Import",
  },
  zh: {
    setPW: "设置密码",
    changePW: "修改密码",
    share: "分享",
    lastModified: "上次保存",
    copy: "复制",
    emptyPH: "看来你是第一个到这儿的人，写点什么吧...",
    tipEncrypt: "这是一篇加密笔记，你必须先输入密码",
    tip404: "404，你要找的东西并不存在",
    backup: "备份",
    restore: "恢复",
    export_: "导出",
    import_: "导入",
    encrypt: "加密",
    close: "关闭",
    webdavConfig: "WebDAV 配置",
    webdavUrl: "WebDAV 地址",
    username: "用户名",
    password: "密码",
    basePath: "基础路径",
    saveConfig: "保存配置",
    testConn: "测试连接",
    backupNow: "立即备份",
    backupList: "备份列表",
    noBackups: "暂无备份",
    confirmRestore: "确认恢复？当前内容将被覆盖。",
    encryptPw: "加密密码",
    invalidFile: "无效的备份文件",
    wrongPassword: "密码错误或文件损坏",
    exportSuccess: "导出成功",
    importSuccess: "导入成功",
    backupSuccess: "备份成功",
    restoreSuccess: "恢复成功",
    connSuccess: "连接成功",
    connFailed: "连接失败",
    localBackup: "本地导入/导出",
  },
};
